import { IoClose } from "react-icons/io5";

import { FaFilePdf, FaShareAlt } from "react-icons/fa";

function InvoicePreviewModal({ open, onClose, invoice }) {
  if (!open) return null;

  return (
    <div className="fixed inset-0 bg-black/40 backdrop-blur-sm flex justify-center items-center z-50 p-4">
      <div className="bg-white h-[600px] rounded-2xl shadow-2xl w-full max-w-3xl overflow-auto">
        {/* Header */}

        <div className="flex justify-between items-center border-b border-[#00000026] px-6 py-4 p-5">
          <h2 className="text-2xl font-bold">Invoice #{invoice?.id}</h2>

          <div className="flex items-center gap-3">
            <button className="flex items-center gap-2 px-4 py-2 cursor-pointer rounded-lg bg-red-50 text-red-600">
              <FaFilePdf />
              PDF
            </button>

            <button className="flex items-center gap-2 px-4 py-2 rounded-lg cursor-pointer bg-green-50 text-green-600">
              <FaShareAlt />
              Share
            </button>

            <button onClick={onClose} className="cursor-pointer">
              <IoClose size={24} />
            </button>
          </div>
        </div>

        {/* Body */}

        <div className="p-8 space-y-8">
          {/* Company + Invoice */}

          <div className="flex flex-col md:flex-row justify-between">
            <div>
              <h3 className="text-2xl font-bold text-[#4B5EAA]">Thomson Casa</h3>

              <p className="text-gray-500">Chicken Supply Management</p>

              <p className="text-sm text-gray-500 mt-4">123 Market Street</p>

              <p className="text-sm text-gray-500">Chennai, Tamil Nadu</p>

              <p className="text-sm text-gray-500">GST: 33ABCDE1234F1Z5</p>
            </div>

            <div className="text-right">
              <h2 className="text-4xl font-bold">INVOICE</h2>

              <p className="mt-3">Order : {invoice?.id}</p>

              <p>Date : {invoice?.date}</p>

              <p>Due : 15 Jul 2026</p>
            </div>
          </div>

          {/* Bill To */}

          <div className="bg-gray-50 rounded-xl p-5">
            <h4 className="font-semibold text-gray-500 mb-4">BILL TO</h4>

            <h3 className="text-xl font-semibold">{invoice?.customer}</h3>

            <p className="text-gray-500">Customer Address</p>

            <p className="text-gray-500">GST: 33ABCDE5678F1Z5</p>
          </div>

          {/* Item Table */}

          <table className="w-full">
            <thead className="border-b border-[#00000026]">
              <tr>
                <th className="text-left py-3">Item</th>

                <th className="text-left">Weight</th>

                <th className="text-left">Rate</th>

                <th className="text-right">Amount</th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td className="py-4">Dressed Chicken</td>

                <td>95 Kg</td>

                <td>₹350/Kg</td>

                <td className="text-right font-semibold">₹33,250</td>
              </tr>
            </tbody>
          </table>

          {/* Totals */}

          <div className="border-t border-[#00000026] pt-6 space-y-3">
            <div className="flex justify-between">
              <span>Subtotal</span>

              <span>₹33,250</span>
            </div>

            <div className="flex justify-between text-red-500">
              <span>Advance Used</span>

              <span>-₹15,000</span>
            </div>

            <div className="flex justify-between text-2xl font-bold border-t border-[#00000026] pt-4">
              <span>Balance Due</span>

              <span>₹18,250</span>
            </div>
          </div>

          {/* Footer */}

          <div className="border-t border-[#00000026] pt-5 flex justify-between text-sm text-gray-400">
            <span>Generated by Thomson Casa ERP</span>

            <span>GST Invoice</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default InvoicePreviewModal;
